task1 Левашов Артём
mipt-diht/mipt-latex-fall2018-soft1q pull request #1
Opened 2018-10-25 15:57 UTC by soft1q

2018-10-25 16:02 UTC, AShepelevv requested changes

2018-10-25 16:02 UTC, AShepelevv commented on task1.tex
> +	\hspace{28pt} \textbf{\large{Термодинамика}}
Тут теперь не 28pt, а 28pt + абзацный отступ. Должно быть просто 28pt.

2018-10-25 16:02 UTC, AShepelevv commented on task1.tex
> +	\hspace{28pt} \textbf{\large{Геометрия}} \hfill \textbf{\large{Планиметрия}}
А можно два раза не писать `\textbf{\large{`?

2018-10-25 16:02 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
А как это без окружения сделать?

2018-10-25 16:02 UTC, AShepelevv commented on task1.tex
> +	\par Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha$,
Не курсив, а наклонный.

2018-10-25 16:02 UTC, AShepelevv commented on task1.tex
> +	Это мой первый документ в системе компьютерный вёрстки \LaTeX.
Нет абзацного отступа.

2018-10-25 16:02 UTC, AShepelevv commented on task1.tex
> +	\par Для \textit{плоского} треугольника со сторонами $a, b, c$ и углом $\alpha$,
Внутри формулы пробелы игнорируются, а на печати они должны быть. (Каждую переменную нужно в отдельную формулу)

2018-10-26 08:56 UTC, soft1q commented
Сделал все исправления, запрошенные @AShepelevv

2018-10-29 14:44 UTC, AShepelevv requested changes

2018-10-29 14:44 UTC, AShepelevv commented on task1.tex
> +	\flushleft{На сегодня, пожалуй, хватит\dots Удачи!}
Хитро, но это не выход.

2018-10-29 14:44 UTC, AShepelevv commented on task1.tex
> +	\par Для \textsl{плоского} треугольника со сторонами $a,$ $b,$ $c$ и углом $\alpha$,
Знаки препинания лучше выносить из формул.

2018-10-29 14:44 UTC, AShepelevv commented on task1.tex
> +	\flushleft{На сегодня, пожалуй, хватит\dots Удачи!}
Как по-другому бороться с отступом?

2018-11-08 09:04 UTC, soft1q commented
Внес исправления

2018-11-09 21:29 UTC, merged