Updating task2 v1.0
mipt-diht/mipt-latex-fall2018-soft1q pull request #2
Opened 2018-10-29 08:13 UTC by soft1q

2018-11-04 07:50 UTC, AShepelevv requested changes

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +	footskip = 0cm
Исправь footskip, чтобы номер страницы не накладывался на текст.

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +	{{\bfseries \large \underline{Задача \thesection.\arabic{num} #1}}\\}%
Сделай небольшой вертикальный отступ после названия задачи, чтобы текст не сливался в одну большую кучу из-за подчеркивания.

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +\DeclareMathOperator{\D}{\mathsf{D}}
Мат ожидание и дисперсия в виде букв E и D не являются как таковыми операторами, то есть после них не должность горизонтального отступа. Здесь лучше `\E` и `\D` сделать просто командами.

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +\DeclareMathOperator{\R}{\mathbb{R}}
Множества натуральный и вещественных чисел уж точно не операторы.

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +\DeclareMathOperator{\Mat}{\text{Mat}}
А  вот Mat должен быть оператором, а у тебя он написан не пойми как.
`\DeclareMathOperator{\Mat}{Mat}`

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +		Пусть $\{\xi_k\}_{k \geq 1}$ ~--- независимые случайные величины,
Перед неразрывным пробелом не должно быть обычного пробела.

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +		Параметры орбиты Венеры: большая полуось $ a = 0.7 $ а.е., эксцентриситет $ e = 0 $, наклон к
Наименования лучше "приклеивать" к числу неразрывным пробелом.

2018-11-04 07:50 UTC, AShepelevv commented on task2.tex
> +		\item[d)] В плане организации и преподаваемого материала все замечательно
Ататата писать буквы вручную. Для этого же есть переопределение счетчиков.

2018-11-13 16:11 UTC, soft1q commented on task2.tex
> +\DeclareMathOperator{\Mat}{\text{Mat}}
Ты привел пример как нужно, или как неправильно? Просто я подумал, что суть Mat как оператора в том, чтобы он писался не шрифтом формулы, а обычным текстом

2018-11-13 16:12 UTC, soft1q commented on task2.tex
> +		\item[d)] В плане организации и преподаваемого материала все замечательно
В смысле надо переопределить счетчик для списка? (а так можно вообще 0_0) Просто в задании указано что-то в духе оформить список в своем стиле, а я не нашел ничего лучше чем вот это

2018-11-13 16:20 UTC, AShepelevv commented on task2.tex
> +		\item[d)] В плане организации и преподаваемого материала все замечательно
В задании написано разные символы использовать для каждого пункта.
А чтобы переопределись счетчик, нужно `\renewcommand{\theenumi}{\roman{\enumi})}`

2018-11-13 16:21 UTC, AShepelevv commented on task2.tex
> +\DeclareMathOperator{\Mat}{\text{Mat}}
Так он и так запишется прямым шрифтом, потому что ты определяешь оператор. `\text{}` – лишнее

2018-11-13 16:47 UTC, AShepelevv requested changes

2018-11-13 16:47 UTC, AShepelevv commented on task2.tex
> +		$\varphi_{\vec\xi}(\vec t) = \exp \left(i(\vec m, \vec t) - \frac{1}{2}(\Sigma\vec t, \vec t)
После векторов поставь `\,`, чтобы стрелочка не выходила за скобку.

2018-11-13 16:59 UTC, soft1q commented
Вроде исправил все запрошенное @AShepelevv

2018-11-13 17:00 UTC, AShepelevv commented
Даже лишнее: после `\vec m` то зачем `\,`, там же дальше запятая идет, а перед знаками препинания пробелы не ставятся.

2018-11-13 17:13 UTC, AShepelevv commented
Перед дифференциалом в интеграле ставиться `\,` –  половинный пробел. Просто запомни это, а ветку я солью поставлю 10)

2018-11-13 17:14 UTC, merged